### ISSUE TITLE
License for core dump script

### ISSUE THREAD

**Issue by igrr** [gsmcmullin/gdb_chibios#1]
Hi @gsmcmullin, we would like to extend your core dump script to support Xtensa architecture and use it in https://github.com/espressif/esp-idf. Unfortunately we couldn't find any license grant in this repository. Could you please clarify the license terms for these scripts?
Thanks!

**Comment by gsmcmullin** [comment]
Hi @igrr.  I'm not too bothered about the use or distribution of these scripts, you may use them under any OSI approved license you prefer.
